version: '3.3'

volumes:
  data:

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db_url_shortener
      - MYSQL_ROOT_PASSWORD=rootpassword

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: urlshortener-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  # myadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   links:
  #     - mysql
  #   ports:
  #     - 80:80
  #   environment:
  #     - PMA_ARBITRARY=1      